<?php

namespace Database\Seeders;

use App\Enums\PermissionType;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $permissions = [
            [
                'title'      => 'Dashboard',
                'name'       => 'dashboard',
                'type'       => PermissionType::BOTH,
                'guard_name' => 'sanctum',
                'url'        => 'dashboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Restaurants',
                'name'       => 'restaurants',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'restaurants',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Restaurants Create',
                        'name'       => 'restaurants_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurants/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Restaurants Edit',
                        'name'       => 'restaurants_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurants/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Restaurants Delete',
                        'name'       => 'restaurants_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurants/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Restaurants Show',
                        'name'       => 'restaurants_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurants/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Cuisines',
                'name'       => 'cuisines',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'cuisines',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Cuisines Create',
                        'name'       => 'cuisines_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'cuisines/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Cuisines Edit',
                        'name'       => 'cuisines_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'cuisines/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Cuisines Delete',
                        'name'       => 'cuisines_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'cuisines/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Cuisines Show',
                        'name'       => 'cuisines_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'cuisines/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Order Tracker',
                'name'       => 'order-tracker',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'order-tracker',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Return Orders',
                'name'       => 'return-orders',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'return-orders',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Return Orders Create',
                        'name'       => 'return-orders_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'return-orders/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Return Orders Delete',
                        'name'       => 'return-orders_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'return-orders/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Return Orders Show',
                        'name'       => 'return-orders_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'return-orders/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Refunds',
                'name'       => 'refunds',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'refunds',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Refunds Create',
                        'name'       => 'refunds_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'refunds/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Refunds Delete',
                        'name'       => 'refunds_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'refunds/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Refunds Show',
                        'name'       => 'refunds_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'refunds/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Reviews',
                'name'       => 'reviews',
                'type'       => PermissionType::BOTH,
                'guard_name' => 'sanctum',
                'url'        => 'reviews',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Reviews Create',
                        'name'       => 'reviews_create',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'reviews/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Reviews Edit',
                        'name'       => 'reviews_edit',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'reviews/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Reviews Delete',
                        'name'       => 'reviews_delete',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'reviews/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Reviews Show',
                        'name'       => 'reviews_show',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'reviews/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Items',
                'name'       => 'items',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'items',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Items Create',
                        'name'       => 'items_create',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'items/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Items Edit',
                        'name'       => 'items_edit',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'items/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Items Delete',
                        'name'       => 'items_delete',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'items/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Items Show',
                        'name'       => 'items_show',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'items/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'POS',
                'name'       => 'pos',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'pos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'POS Orders',
                'name'       => 'pos-orders',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'pos-orders',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Pos Orders Delete',
                        'name'       => 'pos-orders_delete',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'pos-orders/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Pos Orders Show',
                        'name'       => 'pos-orders_show',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'pos-orders/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                ]
            ],
            [
                'title'      => 'Online Orders',
                'name'       => 'online-orders',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'online-orders',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Available Orders',
                'name'       => 'available-orders',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'available-orders',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Active Orders',
                'name'       => 'active-orders',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'active-orders',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Vouchers',
                'name'       => 'vouchers',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'vouchers',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Vouchers Create',
                        'name'       => 'vouchers_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'vouchers/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Vouchers Edit',
                        'name'       => 'vouchers_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'vouchers/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Vouchers Delete',
                        'name'       => 'vouchers_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'vouchers/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Vouchers Show',
                        'name'       => 'vouchers_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'vouchers/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Coupons',
                'name'       => 'coupons',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'coupons',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Coupons Create',
                        'name'       => 'coupons_create',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'coupons/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Coupons Edit',
                        'name'       => 'coupons_edit',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'coupons/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Coupons Delete',
                        'name'       => 'coupons_delete',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'coupons/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Coupons Show',
                        'name'       => 'coupons_show',
                        'type'       => PermissionType::RESTAURANT_OWNER,
                        'guard_name' => 'sanctum',
                        'url'        => 'coupons/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Offers',
                'name'       => 'offers',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'offers',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Offers Create',
                        'name'       => 'offers_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'offers/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Offers Edit',
                        'name'       => 'offers_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'offers/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Offers Delete',
                        'name'       => 'offers_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'offers/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Offers Show',
                        'name'       => 'offers_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'offers/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Campaigns',
                'name'       => 'campaigns',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'campaigns',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Campaigns Create',
                        'name'       => 'campaigns_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'campaigns/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Campaigns Edit',
                        'name'       => 'campaigns_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'campaigns/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Campaigns Delete',
                        'name'       => 'campaigns_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'campaigns/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Campaigns Show',
                        'name'       => 'campaigns_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'campaigns/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Campaigns And Offers',
                'name'       => 'campaigns-and-offers',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'campaigns-and-offers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Push Notifications',
                'name'       => 'push-notifications',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'push-notifications',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Push Notifications Create',
                        'name'       => 'push-notifications_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'push-notifications/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Push Notifications Edit',
                        'name'       => 'push-notifications_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'push-notifications/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Push Notifications Delete',
                        'name'       => 'push-notifications_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'push-notifications/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Push Notifications Show',
                        'name'       => 'push-notifications_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'push-notifications/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Subscribers',
                'name'       => 'subscribers',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'subscribers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Messages',
                'name'       => 'messages',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'messages',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Administrators',
                'name'       => 'administrators',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'administrators',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Administrators Create',
                        'name'       => 'administrators_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'administrators/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Administrators Edit',
                        'name'       => 'administrators_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'administrators/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Administrators Delete',
                        'name'       => 'administrators_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'administrators/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Administrators Show',
                        'name'       => 'administrators_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'administrators/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Delivery Boys',
                'name'       => 'delivery-boys',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'delivery-boys',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Delivery Boys Create',
                        'name'       => 'delivery-boys_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'delivery-boys/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Delivery Boys Edit',
                        'name'       => 'delivery-boys_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'delivery-boys/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Delivery Boys Delete',
                        'name'       => 'delivery-boys_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'delivery-boys/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Delivery Boys Show',
                        'name'       => 'delivery-boys_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'delivery-boys/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Customers',
                'name'       => 'customers',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'customers',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Customers Create',
                        'name'       => 'customers_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'customers/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Customers Edit',
                        'name'       => 'customers_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'customers/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Customers Delete',
                        'name'       => 'customers_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'customers/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Customers Show',
                        'name'       => 'customers_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'customers/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Employees',
                'name'       => 'employees',
                'type'       => PermissionType::BOTH,
                'guard_name' => 'sanctum',
                'url'        => 'employees',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Employees Create',
                        'name'       => 'employees_create',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'employees/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Employees Edit',
                        'name'       => 'employees_edit',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'employees/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Employees Delete',
                        'name'       => 'employees_delete',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'employees/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Employees Show',
                        'name'       => 'employees_show',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'employees/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Tables',
                'name'       => 'tables',
                'type'       => PermissionType::BOTH,
                'guard_name' => 'sanctum',
                'url'        => 'tables',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Tables Create',
                        'name'       => 'tables_create',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Tables Edit',
                        'name'       => 'tables_edit',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Tables Delete',
                        'name'       => 'tables_delete',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Tables Show',
                        'name'       => 'tables_show',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Table QR View',
                        'name'       => 'table_qr_view',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/qr',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Table QR Generate',
                        'name'       => 'table_qr_generate',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/qr/generate',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Table QR Download',
                        'name'       => 'table_qr_download',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/qr/download',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Table QR Regenerate',
                        'name'       => 'table_qr_regenerate',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'tables/qr/regenerate',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Restaurant Owners',
                'name'       => 'restaurant-owners',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'restaurant-owners',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Restaurant Owners Create',
                        'name'       => 'restaurant-owners_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurant-owners/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Restaurant Owners Edit',
                        'name'       => 'restaurant-owners_edit',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurant-owners/edit',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Restaurant Owners Delete',
                        'name'       => 'restaurant-owners_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurant-owners/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Restaurant Owners Show',
                        'name'       => 'restaurant-owners_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'restaurant-owners/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Transactions',
                'name'       => 'transactions',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'transactions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Statements',
                'name'       => 'statements',
                'type'       => PermissionType::BOTH,
                'guard_name' => 'sanctum',
                'url'        => 'statements',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Payouts',
                'name'       => 'payouts',
                'type'       => PermissionType::BOTH,
                'guard_name' => 'sanctum',
                'url'        => 'payouts',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Payouts Create',
                        'name'       => 'payouts_create',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'payouts/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Payouts Delete',
                        'name'       => 'payouts_delete',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'payouts/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Payouts Show',
                        'name'       => 'payouts_show',
                        'type'       => PermissionType::BOTH,
                        'guard_name' => 'sanctum',
                        'url'        => 'payouts/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Collections',
                'name'       => 'collections',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'collections',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Collections Create',
                        'name'       => 'collections_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'collections/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Collections Delete',
                        'name'       => 'collections_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'collections/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Cashouts',
                'name'       => 'cashouts',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'cashouts',
                'created_at' => now(),
                'updated_at' => now(),
                'children'   => [
                    [
                        'title'      => 'Cashouts Create',
                        'name'       => 'cashouts_create',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'cashouts/create',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Cashouts Delete',
                        'name'       => 'cashouts_delete',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'cashouts/delete',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'title'      => 'Cashouts Show',
                        'name'       => 'cashouts_show',
                        'type'       => PermissionType::ADMIN,
                        'guard_name' => 'sanctum',
                        'url'        => 'cashouts/show',
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                ]
            ],
            [
                'title'      => 'Credit Balance Report',
                'name'       => 'credit-balance-report',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'credit-balance-report',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Collection Report',
                'name'       => 'collection-report',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'collection-report',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Sales Report',
                'name'       => 'sales-report',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'sales-report',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Items Report',
                'name'       => 'items-report',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'items-report',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'System Settings',
                'name'       => 'system_settings',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'system-settings',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Restaurant Settings',
                'name'       => 'restaurant-settings',
                'type'       => PermissionType::RESTAURANT_OWNER,
                'guard_name' => 'sanctum',
                'url'        => 'restaurant-settings',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title'      => 'Delivery Boy Settings',
                'name'       => 'delivery-boy-settings',
                'type'       => PermissionType::ADMIN,
                'guard_name' => 'sanctum',
                'url'        => 'delivery-boy-settings',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        // Migrations may already have created tables/QR/waiter/kitchen permissions.
        // Upsert by name so migrate:fresh --seed does not hit unique constraint errors,
        // and parent ids point at real rows instead of assumed auto-increment indexes.
        foreach ($permissions as $permission) {
            $children = $permission['children'] ?? [];
            unset($permission['children']);

            $parent = Permission::query()->firstOrCreate(
                [
                    'name'       => $permission['name'],
                    'guard_name' => $permission['guard_name'] ?? 'sanctum',
                ],
                array_merge($permission, ['parent' => 0])
            );

            if ((int) $parent->parent !== 0) {
                $parent->update(['parent' => 0]);
            }

            foreach ($children as $child) {
                $childModel = Permission::query()->firstOrCreate(
                    [
                        'name'       => $child['name'],
                        'guard_name' => $child['guard_name'] ?? 'sanctum',
                    ],
                    array_merge($child, ['parent' => $parent->id])
                );

                if ((int) $childModel->parent !== (int) $parent->id) {
                    $childModel->update(['parent' => $parent->id]);
                }
            }
        }
    }
}
