<?php

namespace App\Traits\Seeder;

use App\Enums\Ask;
use App\Enums\DiscountType;
use App\Enums\Status;
use App\Enums\ItemType;

trait ItemSeederTraitEight
{
    public array $itemSeederEight = [
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Fried Cheese wonton',
                'item_category_id'          => 58,
                'tax_index'                 => 1,
                'price'                     => 4.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 8 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 12 pcs',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Egg Roll',
                'item_category_id'          => 58,
                'tax_index'                 => 1,
                'price'                     => 13.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 4,
                    'name'                 => 'Chicken',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 4,
                    'name'                 => 'Beef',
                    'price'                => 4.00,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Chicken Dumplings',
                'item_category_id'          => 58,
                'tax_index'                 => 1,
                'price'                     => 12.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => '16:00:00',
                'available_time_end'        => '20:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 8 pcs',
                    'price'                => 2.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 12 pcs',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Vegetable Dumplings',
                'item_category_id'          => 58,
                'tax_index'                 => 1,
                'price'                     => 13.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Half - 6 pcs',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Full - 12 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 8,
                'name'                      => 'Vegetable Roll',
                'item_category_id'          => 58,
                'tax_index'                 => 2,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Ultimate Pepperoni Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '06:00:00',
                'available_time_end'        => '12:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Facilitating social connection and bonding, food creates opportunities for shared moments of joy and togetherness.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Extra Cheesy Alfredo Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::FIXED,
                'discount'                  => 2,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'A canvas for creativity and innovation, food inspires chefs and home cooks to experiment with flavors and techniques.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Super Hawaiian Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Garden Fresh Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'The Works Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 11.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'BBQ Chicken Bacon Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 13.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 30,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Philly Cheesesteak Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 15.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Meatball Pepperoni Pizza',
                'item_category_id'          => 59,
                'tax_index'                 => 4,
                'price'                     => 12.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Olive and Spinach Quesadilla',
                'item_category_id'          => 60,
                'tax_index'                 => 0,
                'price'                     => 5.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Italian Chicken Quesadilla',
                'item_category_id'          => 60,
                'tax_index'                 => 0,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Cheese Quesadilla',
                'item_category_id'          => 60,
                'tax_index'                 => 2,
                'price'                     => 7.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the catalyst for social interaction and bonding, fostering connections, fostering connections, fostering connections, and strengthening relationships through shared meals, conversations, and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 4.00,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 3.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Beef Quesadilla',
                'item_category_id'          => 60,
                'tax_index'                 => 0,
                'price'                     => 6.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 4.00,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 3.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Ham, Egg & Cheddar Cheese Burrito',
                'item_category_id'          => 61,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Sausage, Egg & Cheddar Burrito',
                'item_category_id'          => 61,
                'tax_index'                 => 3,
                'price'                     => 5.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Loaded Veggie Burrito',
                'item_category_id'          => 61,
                'tax_index'                 => 4,
                'price'                     => 5.30,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'A canvas for creativity and innovation, food inspires chefs and home cooks to experiment with flavors and techniques.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Meat Eaters Burrito',
                'item_category_id'          => 61,
                'tax_index'                 => 3,
                'price'                     => 3.30,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 10,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 8,
                'name'                      => 'Baked Potato',
                'item_category_id'          => 62,
                'tax_index'                 => 3,
                'price'                     => 3.70,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Facilitating social connection and bonding, food creates opportunities for shared moments of joy and togetherness.',
            ]
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'French Fries',
                'item_category_id'          => 62,
                'tax_index'                 => 3,
                'price'                     => 4.70,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => 'LMIV - Allergen - i). Contains cereals and products thereof containing gluten ii). Wheat',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 8,
                'name'                      => 'Homemade Mashed Potato',
                'item_category_id'          => 62,
                'tax_index'                 => 3,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ]
        ],

        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Onion Rings',
                'item_category_id'          => 62,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'A canvas for creativity and innovation, food inspires chefs and home cooks to experiment with flavors and techniques.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 8,
                'name'                      => 'Potato Pancakes',
                'item_category_id'          => 62,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ]
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Strawberry Milkshake',
                'item_category_id'          => 63,
                'tax_index'                 => 1,
                'price'                     => 3.80,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Vanilla Milkshake',
                'item_category_id'          => 63,
                'tax_index'                 => 1,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Chocolate Milkshake',
                'item_category_id'          => 63,
                'tax_index'                 => 0,
                'price'                     => 3.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Banana Milkshake',
                'item_category_id'          => 63,
                'tax_index'                 => 1,
                'price'                     => 3.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 8,
                'name'                      => 'Blueberry Milkshake',
                'item_category_id'          => 63,
                'tax_index'                 => 1,
                'price'                     => 3.70,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],

    ];
}
