<?php

namespace App\Traits\Seeder;

use App\Enums\Ask;
use App\Enums\Status;
use App\Enums\ItemType;
use App\Enums\DiscountType;

trait ItemSeederTraitNineteen
{
    public array $itemSeederNineteen = [
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Fried Cheese wonton',
                'item_category_id'          => 132,
                'tax_index'                 => 1,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 8 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 12 pcs',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Egg Roll',
                'item_category_id'          => 132,
                'tax_index'                 => 1,
                'price'                     => 13.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 40,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 4,
                    'name'                 => 'Chicken',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 4,
                    'name'                 => 'Beef',
                    'price'                => 4.00,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Chicken Dumplings',
                'item_category_id'          => 132,
                'tax_index'                 => 1,
                'price'                     => 12.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::FIXED,
                'discount'                  => 5.50,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 8 pcs',
                    'price'                => 2.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 12 pcs',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Vegetable Dumplings',
                'item_category_id'          => 132,
                'tax_index'                 => 1,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Half - 6 pcs',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Full - 12 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Vegetable Roll',
                'item_category_id'          => 132,
                'tax_index'                 => 2,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Szechuan Shrimp',
                'item_category_id'          => 133,
                'tax_index'                 => 0,
                'price'                     => 12.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains crustaceans and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 6',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 12',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'  => [
                'restaurant_id'             => 19,
                'name'                      => 'Salmon with Mix Vegetables',
                'item_category_id'          => 133,
                'tax_index'                 => 0,
                'price'                     => 12.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'extra' => [
                [
                    'name'   => 'Avocado',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Chilli fries',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Shrimp with Brocolli',
                'item_category_id'          => 133,
                'tax_index'                 => 0,
                'price'                     => 53.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '13:00:00',
                'available_time_end'        => '16:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 50,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains crustaceans and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 6',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 12',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Kung Pao Squid',
                'item_category_id'          => 133,
                'tax_index'                 => 0,
                'price'                     => 13.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 6',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 12',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Chicken Gyro Plate with Fries',
                'item_category_id'          => 134,
                'tax_index'                 => 0,
                'price'                     => 12.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],

        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Lamb Gyro Plate with Fries',
                'item_category_id'          => 134,
                'tax_index'                 => 0,
                'price'                     => 16.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Chicken Gyro Sandwich',
                'item_category_id'          => 134,
                'tax_index'                 => 0,
                'price'                     => 11.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Half',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Full',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Lamb Gyro Sandwich',
                'item_category_id'          => 134,
                'tax_index'                 => 0,
                'price'                     => 11.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Western Omelette',
                'item_category_id'          => 135,
                'tax_index'                 => 1,
                'price'                     => 6.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Onion & Swiss Cheese Omelette',
                'item_category_id'          => 135,
                'tax_index'                 => 1,
                'price'                     => 6.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Classic Cheese Omelette',
                'item_category_id'          => 135,
                'tax_index'                 => 2,
                'price'                     => 7.80,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Bacon & Tomato Omelette',
                'item_category_id'          => 135,
                'tax_index'                 => 2,
                'price'                     => 5.80,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Greek Omelette',
                'item_category_id'          => 135,
                'tax_index'                 => 1,
                'price'                     => 6.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Mix Vegetables Salad',
                'item_category_id'          => 136,
                'tax_index'                 => 0,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Classic Ceasar Salad',
                'item_category_id'          => 136,
                'tax_index'                 => 0,
                'price'                     => 6.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 5,
                    'name'                 => 'No egg',
                    'price'                => 0.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 5,
                    'name'                 => 'Poached egg',
                    'price'                => 1.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Fresh Tuna Salad',
                'item_category_id'          => 136,
                'tax_index'                 => 0,
                'price'                     => 11.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '12:00:00',
                'available_time_end'        => '15:00:00',
                'discount_type'             => DiscountType::FIXED,
                'discount'                  => 5,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Poached Pear Salad',
                'item_category_id'          => 136,
                'tax_index'                 => 0,
                'price'                     => 12.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Roasted Salmon Salad',
                'item_category_id'          => 136,
                'tax_index'                 => 0,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Potato Pancakes',
                'item_category_id'          => 137,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ]
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'French Fries',
                'item_category_id'          => 137,
                'tax_index'                 => 3,
                'price'                     => 4.70,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Homemade Mashed Potato',
                'item_category_id'          => 137,
                'tax_index'                 => 3,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ]
        ],
        [
            'item' => [
                'restaurant_id'             => 19,
                'name'                      => 'Baked Potato',
                'item_category_id'          => 137,
                'tax_index'                 => 3,
                'price'                     => 3.70,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Facilitating social connection and bonding, food creates opportunities for shared moments of joy and togetherness.',
            ]
        ],
        [
            'item'      => [
                'restaurant_id'             => 19,
                'name'                      => 'Onion Rings',
                'item_category_id'          => 137,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'A canvas for creativity and innovation, food inspires chefs and home cooks to experiment with flavors and techniques.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
    ];
}
