<?php

namespace App\Traits\Seeder;

use App\Enums\Ask;
use App\Enums\DiscountType;
use App\Enums\Status;
use App\Enums\ItemType;

trait ItemSeederTraitNine
{
    public array $itemSeederNine = [
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Western Omelette',
                'item_category_id'          => 64,
                'tax_index'                 => 1,
                'price'                     => 6.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Onion & Swiss Cheese Omelette',
                'item_category_id'          => 64,
                'tax_index'                 => 1,
                'price'                     => 6.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 30,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Classic Cheese Omelette',
                'item_category_id'          => 64,
                'tax_index'                 => 2,
                'price'                     => 7.80,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Bacon & Tomato Omelette',
                'item_category_id'          => 64,
                'tax_index'                 => 2,
                'price'                     => 5.80,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Greek Omelette',
                'item_category_id'          => 64,
                'tax_index'                 => 1,
                'price'                     => 6.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Cheese Quesadilla',
                'item_category_id'          => 65,
                'tax_index'                 => 2,
                'price'                     => 7.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the catalyst for social interaction and bonding, fostering connections, fostering connections, fostering connections, and strengthening relationships through shared meals, conversations, and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 4.00,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 3.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Olive and Spinach Quesadilla',
                'item_category_id'          => 65,
                'tax_index'                 => 0,
                'price'                     => 5.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Italian Chicken Quesadilla',
                'item_category_id'          => 65,
                'tax_index'                 => 0,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Beef Quesadilla',
                'item_category_id'          => 65,
                'tax_index'                 => 0,
                'price'                     => 6.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::FIXED,
                'discount'                  => 2,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 4.00,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 3.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Ham, Egg & Cheddar Cheese Burrito',
                'item_category_id'          => 66,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Sausage, Egg & Cheddar Burrito',
                'item_category_id'          => 66,
                'tax_index'                 => 3,
                'price'                     => 5.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Bacon, Egg & Cheddar Burrito',
                'item_category_id'          => 66,
                'tax_index'                 => 0,
                'price'                     => 5.30,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Food is the catalyst for social interaction and bonding, fostering connections, fostering connections, fostering connections, and strengthening relationships through shared meals, conversations, and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.75,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.65,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onion',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Loaded Veggie Burrito',
                'item_category_id'          => 66,
                'tax_index'                 => 4,
                'price'                     => 5.30,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'A canvas for creativity and innovation, food inspires chefs and home cooks to experiment with flavors and techniques.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Meat Eaters Burrito',
                'item_category_id'          => 66,
                'tax_index'                 => 3,
                'price'                     => 3.30,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => '14:00:00',
                'available_time_end'        => '20:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.30,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.20,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 0.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.35,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 1.85,
                    'status' => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Poached Pear Salad',
                'item_category_id'          => 67,
                'tax_index'                 => 0,
                'price'                     => 12.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Classic Ceasar Salad',
                'item_category_id'          => 67,
                'tax_index'                 => 0,
                'price'                     => 6.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 5,
                    'name'                 => 'No egg',
                    'price'                => 0.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 5,
                    'name'                 => 'Poached egg',
                    'price'                => 1.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Fresh Tuna Salad',
                'item_category_id'          => 67,
                'tax_index'                 => 0,
                'price'                     => 11.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Roasted Salmon Salad',
                'item_category_id'          => 67,
                'tax_index'                 => 0,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Mix Vegetables Salad',
                'item_category_id'          => 67,
                'tax_index'                 => 0,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains nuts and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Cashews</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Onion Rings',
                'item_category_id'          => 68,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'A canvas for creativity and innovation, food inspires chefs and home cooks to experiment with flavors and techniques.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Potato Pancakes',
                'item_category_id'          => 68,
                'tax_index'                 => 3,
                'price'                     => 4.40,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ]
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'French Fries',
                'item_category_id'          => 68,
                'tax_index'                 => 3,
                'price'                     => 4.70,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Homemade Mashed Potato',
                'item_category_id'          => 68,
                'tax_index'                 => 3,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ]
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Baked Potato',
                'item_category_id'          => 68,
                'tax_index'                 => 3,
                'price'                     => 3.70,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Facilitating social connection and bonding, food creates opportunities for shared moments of joy and togetherness.',
            ]
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Iced Coffee',
                'item_category_id'          => 69,
                'tax_index'                 => 4,
                'price'                     => 3.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 3.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.70,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Soda (Can)',
                'item_category_id'          => 69,
                'tax_index'                 => 4,
                'price'                     => 2.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ]
        ],
        [
            'item'      => [
                'restaurant_id'             => 9,
                'name'                      => 'Homemade Lemonade',
                'item_category_id'          => 69,
                'tax_index'                 => 4,
                'price'                     => 2.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Soda (Bottle)',
                'item_category_id'          => 69,
                'tax_index'                 => 4,
                'price'                     => 3.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
        ],

        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Chai Latte',
                'item_category_id'          => 69,
                'tax_index'                 => 4,
                'price'                     => 2.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ]
        ],
        [
            'item' => [
                'restaurant_id'             => 9,
                'name'                      => 'Cappuccino',
                'item_category_id'          => 69,
                'tax_index'                 => 4,
                'price'                     => 2.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ]
        ],
    ];
}
