<?php

namespace App\Traits\Seeder;

use App\Enums\Ask;
use App\Enums\DiscountType;
use App\Enums\Status;
use App\Enums\ItemType;

trait ItemSeederTraitSeven
{
    public array $itemSeederSeven = [
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Fried Cheese wonton',
                'item_category_id'          => 51,
                'tax_index'                 => 1,
                'price'                     => 4.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 8 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 12 pcs',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Egg Roll',
                'item_category_id'          => 51,
                'tax_index'                 => 1,
                'price'                     => 13.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 4,
                    'name'                 => 'Chicken',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 4,
                    'name'                 => 'Beef',
                    'price'                => 4.00,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Chicken Dumplings',
                'item_category_id'          => 51,
                'tax_index'                 => 1,
                'price'                     => 12.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 8 pcs',
                    'price'                => 2.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular - 12 pcs',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Vegetable Dumplings',
                'item_category_id'          => 51,
                'tax_index'                 => 1,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Half - 6 pcs',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Full - 12 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 7,
                'name'                      => 'Vegetable Roll',
                'item_category_id'          => 51,
                'tax_index'                 => 2,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::FIXED,
                'discount'                  => 2,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Sweet & Sour Chicken',
                'item_category_id'          => 52,
                'tax_index'                 => 3,
                'price'                     => 13.45,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '06:00:00',
                'available_time_end'        => '11:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => '6 pcs',
                    'price'                => 3.54,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '8 pcs',
                    'price'                => 4.20,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '12 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Yemete Kudasai Chicken',
                'item_category_id'          => 52,
                'tax_index'                 => 2,
                'price'                     => 3.45,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => '07:00:00',
                'available_time_end'        => '12:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => '6 pcs',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '8 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '12 pcs',
                    'price'                => 4.90,
                    'status'               => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Sesame Chicken',
                'item_category_id'          => 52,
                'tax_index'                 => 3,
                'price'                     => 4.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '08:00:00',
                'available_time_end'        => '13:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => '6 pcs',
                    'price'                => 4.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '8 pcs',
                    'price'                => 6.80,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '12 pcs',
                    'price'                => 7.00,
                    'status'               => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Hentai Chicken',
                'item_category_id'          => 52,
                'tax_index'                 => 3,
                'price'                     => 12.30,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 20,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => '6 pcs',
                    'price'                => 2.38,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '8 pcs',
                    'price'                => 3.68,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '12 pcs',
                    'price'                => 4.48,
                    'status'               => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Kung Pao Chicken',
                'item_category_id'          => 52,
                'tax_index'                 => 3,
                'price'                     => 4.48,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 20,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => '6 pcs',
                    'price'                => 4.49,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '8 pcs',
                    'price'                => 4.99,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => '12 pcs',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ]
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Beef with Mix Vegetables',
                'item_category_id'          => 53,
                'tax_index'                 => 4,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Food is the catalyst for exploration and adventure, inviting individuals to discover new flavors, textures, and culinary techniques from around the globe.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Large',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Rare',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Medium',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Well',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ]
            ],
            'extra'     => [
                [
                    'name'   => 'Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Mashrooms',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Pepper Steak with Onions',
                'item_category_id'          => 53,
                'tax_index'                 => 4,
                'price'                     => 53.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Large',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Rare',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Medium',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Well',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ]
            ],
            'extra'     => [
                [
                    'name'   => 'Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Mashrooms',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Beef with Brocolli',
                'item_category_id'          => 53,
                'tax_index'                 => 4,
                'price'                     => 14.5,
                'item_type'                 => null,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Large',
                    'price'                => 5.58,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Rare',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Medium',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Well',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ]
            ],
            'extra'     => [
                [
                    'name'   => 'Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Mashrooms',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],

        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Szechuan Beef',
                'item_category_id'          => 53,
                'tax_index'                 => 4,
                'price'                     => 3.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 2,
                    'name'                 => 'Large',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Rare',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Medium',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 3,
                    'name'                 => 'Well',
                    'price'                => 3.00,
                    'status'               => Status::ACTIVE,
                ]
            ],
            'extra'     => [
                [
                    'name'   => 'Onion',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Mashrooms',
                    'price'  => 2.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Kung Pao Squid',
                'item_category_id'          => 54,
                'tax_index'                 => 0,
                'price'                     => 13.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 6',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 12',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'  => [
                'restaurant_id'             => 7,
                'name'                      => 'Salmon with Mix Vegetables',
                'item_category_id'          => 54,
                'tax_index'                 => 0,
                'price'                     => 12.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::FIXED,
                'discount'                  => 2,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains fish and products thereof</span></li><li><span>Contains sulphur dioxide and sulphites</span></li><li><span>Contains soybeans and products thereof</span></li><li><span>Contains milk and products thereof (including lactose)</span></li><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>wheat</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'extra' => [
                [
                    'name'   => 'Avocado',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Chilli fries',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Shrimp with Brocolli',
                'item_category_id'          => 54,
                'tax_index'                 => 0,
                'price'                     => 53.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 30,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains crustaceans and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 6',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 12',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Szechuan Shrimp',
                'item_category_id'          => 54,
                'tax_index'                 => 0,
                'price'                     => 12.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains crustaceans and products thereof</span></li><li><span>Contains sesame seeds and products thereof</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 6',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 1,
                    'name'                 => 'Pack of 12',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Chicken Gyro Plate with Fries',
                'item_category_id'          => 55,
                'tax_index'                 => 0,
                'price'                     => 12.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Lamb Gyro Plate with Fries',
                'item_category_id'          => 55,
                'tax_index'                 => 0,
                'price'                     => 16.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '10:00:00',
                'available_time_end'        => '22:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Chicken Gyro Sandwich',
                'item_category_id'          => 55,
                'tax_index'                 => 0,
                'price'                     => 11.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li><li><span>Contains eggs and products thereof</span></li><li><span>Wheat</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Half',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Full',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Lamb Gyro Sandwich',
                'item_category_id'          => 55,
                'tax_index'                 => 0,
                'price'                     => 11.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>Substances or products causing allergies</span></p><ul><li><span>With nitrite curing salt</span></li><li><span>With nitrate</span></li><li><span>With nitrite curing salt and nitrate</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 5.00,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Big',
                    'price'                => 5.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Extra Cheesy Alfredo Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'A canvas for creativity and innovation, food inspires chefs and home cooks to experiment with flavors and techniques.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'The Works Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 11.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'BBQ Chicken Bacon Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 13.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '13:00:00',
                'available_time_end'        => '19:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::NON_VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Philly Cheesesteak Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 15.50,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => '13:00:00',
                'available_time_end'        => '19:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Meatball Pepperoni Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 12.50,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => '13:00:00',
                'available_time_end'        => '19:00:00',
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Patty',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Super Hawaiian Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Garden Fresh Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => ItemType::VEG,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Essential for life and culture, food encompasses a diverse range of flavors and traditions.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Add Tomato',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Lattuce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Add Onions',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Ultimate Pepperoni Pizza',
                'item_category_id'          => 56,
                'tax_index'                 => 4,
                'price'                     => 12.60,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains cereals and products thereof containing gluten</span></li></ul>',
                'description'               => 'Facilitating social connection and bonding, food creates opportunities for shared moments of joy and togetherness.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
            'extra'     => [
                [
                    'name'   => 'Cheese',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'Bacon',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
                [
                    'name'   => 'BBQ Sauce',
                    'price'  => 1.50,
                    'status' => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 7,
                'name'                      => 'Soda (Bottle)',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 3.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Inspiring exploration and discovery, food invites us to embark on culinary adventures both near and far.',
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 7,
                'name'                      => 'Mojito',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 5.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 10,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Food is the source of comfort, joy, and nostalgia, evoking memories of home-cooked meals, festive gatherings, and cherished moments.',
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 7,
                'name'                      => 'Espresso',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 6.00,
                'is_halal'                  => Ask::YES,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Eliciting comfort and nostalgia, food holds the power to evoke cherished memories and experiences.',
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Iced Coffee',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 3.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Bridging divides and fostering understanding, food serves as a common ground for communication and celebration.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 3.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.70,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item'      => [
                'restaurant_id'             => 7,
                'name'                      => 'Homemade Lemonade',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 2.60,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Vital for health and well-being, food fuels our bodies and minds with essential nutrients and energy.',
            ],
            'variation' => [
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Regular',
                    'price'                => 2.70,
                    'status'               => Status::ACTIVE,
                ],
                [
                    'item_attribute_index' => 0,
                    'name'                 => 'Large',
                    'price'                => 3.50,
                    'status'               => Status::ACTIVE,
                ],
            ],
        ],
        [
            'item' => [
                'restaurant_id'             => 7,
                'name'                      => 'Soda (Can)',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 2.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => null,
                'description'               => 'Reflecting heritage and values, food embodies the richness of cultural diversity across the globe.',
            ]
        ],
        [
            'item' => [
                'restaurant_id'             => 7,
                'name'                      => 'Chai Latte',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 2.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Derived from natures bounty, food provides sustenance while connecting us to our environment.',
            ]
        ],
        [
            'item' => [
                'restaurant_id'             => 7,
                'name'                      => 'Cappuccino',
                'item_category_id'          => 57,
                'tax_index'                 => 4,
                'price'                     => 2.00,
                'is_halal'                  => Ask::NO,
                'available_time_start'      => null,
                'available_time_end'        => null,
                'discount_type'             => DiscountType::PERCENTAGE,
                'discount'                  => 0,
                'maximum_purchase_quantity' => 100,
                'item_type'                 => null,
                'caution'                   => '<p><span>LMIV - Allergen</span></p><ul><li><span>Contains milk and products thereof (including lactose)</span></li></ul>',
                'description'               => 'Satisfying hunger and bringing people together, food is a universal language of nourishment and joy.',
            ]
        ],
    ];
}
